# Generated by Django 6.0.2 on 2026-03-16 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0002_alter_patient_ldl'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=120)),
                ('summary', models.TextField()),
                ('risk_summary', models.TextField()),
                ('key_factors', models.JSONField(blank=True, default=list)),
                ('safety_flags', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_cache', to='patient.patient')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
