import datetime

from django.db import migrations, models


def seed_patients(apps, schema_editor):
    Patient = apps.get_model('patient', 'Patient')

    sample_patients = [
        {
            'patient_code': 'PT-A1F3C2',
            'full_name': 'James Okafor',
            'age': 74,
            'gender': 'M',
            'weight': '82.0',
            'height': '170.0',
            'hba1c': '8.6',
            'systolic_bp': 158,
            'diastolic_bp': 94,
            'heart_rate': 82,
            'fasting_glucose': 162,
            'ldl': 148,
            'creatinine': '1.3',
            'smoking_status': 'Former',
            'adherence': 'Moderate',
            'mobility_status': 'Independent',
            'cognitive_status': 'Mild Impairment',
            'fall_history': '1–2 falls',
            'medications': ['Metformin', 'Amlodipine', 'Lisinopril', 'Atorvastatin', 'Aspirin'],
            'review_status': 'Urgent',
            'last_assessed': datetime.date(2025, 7, 14),
        },
        {
            'patient_code': 'PT-B2D4E8',
            'full_name': 'Amina Bello',
            'age': 68,
            'gender': 'F',
            'weight': '65.0',
            'height': '158.0',
            'hba1c': '7.2',
            'systolic_bp': 138,
            'diastolic_bp': 85,
            'heart_rate': 74,
            'fasting_glucose': 128,
            'ldl': 110,
            'creatinine': '0.9',
            'smoking_status': 'Never',
            'adherence': 'Good',
            'mobility_status': 'Independent',
            'cognitive_status': 'Normal',
            'fall_history': 'None',
            'medications': ['Metformin', 'Ramipril'],
            'review_status': 'Reviewed',
            'last_assessed': datetime.date(2025, 7, 12),
        },
        {
            'patient_code': 'PT-C3F5G1',
            'full_name': 'Emmanuel Adeyemi',
            'age': 81,
            'gender': 'M',
            'weight': '70.0',
            'height': '165.0',
            'hba1c': '9.1',
            'systolic_bp': 172,
            'diastolic_bp': 98,
            'heart_rate': 90,
            'fasting_glucose': 188,
            'ldl': 162,
            'creatinine': '1.6',
            'smoking_status': 'Current',
            'adherence': 'Poor',
            'mobility_status': 'Assisted',
            'cognitive_status': 'Moderate Impairment',
            'fall_history': '3+ falls',
            'medications': ['Insulin glargine', 'Amlodipine', 'Furosemide', 'Warfarin', 'Allopurinol', 'Omeprazole'],
            'review_status': 'Urgent',
            'last_assessed': datetime.date(2025, 7, 15),
        },
        {
            'patient_code': 'PT-D4H6I3',
            'full_name': 'Grace Nwosu',
            'age': 63,
            'gender': 'F',
            'weight': '78.0',
            'height': '162.0',
            'hba1c': '7.8',
            'systolic_bp': 145,
            'diastolic_bp': 88,
            'heart_rate': 76,
            'fasting_glucose': 142,
            'ldl': 128,
            'creatinine': '1.0',
            'smoking_status': 'Never',
            'adherence': 'Good',
            'mobility_status': 'Independent',
            'cognitive_status': 'Normal',
            'fall_history': 'None',
            'medications': ['Metformin', 'Lisinopril', 'Atorvastatin'],
            'review_status': 'Pending',
            'last_assessed': datetime.date(2025, 7, 10),
        },
        {
            'patient_code': 'PT-E5J7K2',
            'full_name': 'Ibrahim Musa',
            'age': 77,
            'gender': 'M',
            'weight': '88.0',
            'height': '172.0',
            'hba1c': '8.3',
            'systolic_bp': 162,
            'diastolic_bp': 96,
            'heart_rate': 84,
            'fasting_glucose': 174,
            'ldl': 155,
            'creatinine': '1.4',
            'smoking_status': 'Former',
            'adherence': 'Moderate',
            'mobility_status': 'Independent',
            'cognitive_status': 'Mild Impairment',
            'fall_history': '1–2 falls',
            'medications': ['Glipizide', 'Losartan', 'Atorvastatin', 'Aspirin', 'Bisoprolol'],
            'review_status': 'Pending',
            'last_assessed': datetime.date(2025, 7, 13),
        },
        {
            'patient_code': 'PT-F6L8M4',
            'full_name': 'Fatima Abdullahi',
            'age': 70,
            'gender': 'F',
            'weight': '60.0',
            'height': '155.0',
            'hba1c': '7.5',
            'systolic_bp': 132,
            'diastolic_bp': 82,
            'heart_rate': 70,
            'fasting_glucose': 132,
            'ldl': 105,
            'creatinine': '0.8',
            'smoking_status': 'Never',
            'adherence': 'Good',
            'mobility_status': 'Independent',
            'cognitive_status': 'Normal',
            'fall_history': 'None',
            'medications': ['Metformin', 'Amlodipine'],
            'review_status': 'Reviewed',
            'last_assessed': datetime.date(2025, 7, 8),
        },
        {
            'patient_code': 'PT-G7N9O5',
            'full_name': 'Sunday Eze',
            'age': 85,
            'gender': 'M',
            'weight': '67.0',
            'height': '168.0',
            'hba1c': '9.4',
            'systolic_bp': 178,
            'diastolic_bp': 102,
            'heart_rate': 92,
            'fasting_glucose': 204,
            'ldl': 170,
            'creatinine': '1.8',
            'smoking_status': 'Former',
            'adherence': 'Poor',
            'mobility_status': 'Wheelchair',
            'cognitive_status': 'Severe',
            'fall_history': '3+ falls',
            'medications': ['Insulin lispro', 'Insulin glargine', 'Furosemide', 'Digoxin', 'Warfarin', 'Allopurinol', 'Omeprazole'],
            'review_status': 'Urgent',
            'last_assessed': datetime.date(2025, 7, 15),
        },
        {
            'patient_code': 'PT-H8P0Q6',
            'full_name': 'Chidinma Obi',
            'age': 65,
            'gender': 'F',
            'weight': '72.0',
            'height': '160.0',
            'hba1c': '7.4',
            'systolic_bp': 136,
            'diastolic_bp': 84,
            'heart_rate': 72,
            'fasting_glucose': 126,
            'ldl': 118,
            'creatinine': '0.9',
            'smoking_status': 'Never',
            'adherence': 'Good',
            'mobility_status': 'Independent',
            'cognitive_status': 'Normal',
            'fall_history': 'None',
            'medications': ['Metformin', 'Losartan'],
            'review_status': 'Reviewed',
            'last_assessed': datetime.date(2025, 7, 9),
        },
        {
            'patient_code': 'PT-I9R1S7',
            'full_name': 'Tunde Fashola',
            'age': 73,
            'gender': 'M',
            'weight': '84.0',
            'height': '174.0',
            'hba1c': '8.0',
            'systolic_bp': 155,
            'diastolic_bp': 92,
            'heart_rate': 80,
            'fasting_glucose': 158,
            'ldl': 140,
            'creatinine': '1.2',
            'smoking_status': 'Former',
            'adherence': 'Moderate',
            'mobility_status': 'Independent',
            'cognitive_status': 'Mild Impairment',
            'fall_history': '1–2 falls',
            'medications': ['Metformin', 'Glibenclamide', 'Atorvastatin', 'Aspirin'],
            'review_status': 'Pending',
            'last_assessed': datetime.date(2025, 7, 11),
        },
        {
            'patient_code': 'PT-J0T2U8',
            'full_name': 'Ngozi Ikenna',
            'age': 67,
            'gender': 'F',
            'weight': '68.0',
            'height': '157.0',
            'hba1c': '7.6',
            'systolic_bp': 140,
            'diastolic_bp': 86,
            'heart_rate': 75,
            'fasting_glucose': 136,
            'ldl': 122,
            'creatinine': '1.0',
            'smoking_status': 'Never',
            'adherence': 'Good',
            'mobility_status': 'Independent',
            'cognitive_status': 'Normal',
            'fall_history': 'None',
            'medications': ['Metformin', 'Ramipril', 'Atorvastatin'],
            'review_status': 'Reviewed',
            'last_assessed': datetime.date(2025, 7, 7),
        },
        {
            'patient_code': 'PT-K1V3W9',
            'full_name': 'Clement Okonkwo',
            'age': 79,
            'gender': 'M',
            'weight': '76.0',
            'height': '169.0',
            'hba1c': '8.8',
            'systolic_bp': 166,
            'diastolic_bp': 97,
            'heart_rate': 86,
            'fasting_glucose': 180,
            'ldl': 158,
            'creatinine': '1.5',
            'smoking_status': 'Current',
            'adherence': 'Poor',
            'mobility_status': 'Assisted',
            'cognitive_status': 'Moderate Impairment',
            'fall_history': '3+ falls',
            'medications': ['Insulin glargine', 'Amlodipine', 'Furosemide', 'Atorvastatin', 'Aspirin', 'Omeprazole'],
            'review_status': 'Urgent',
            'last_assessed': datetime.date(2025, 7, 14),
        },
        {
            'patient_code': 'PT-L2X4Y0',
            'full_name': 'Blessing Chukwu',
            'age': 62,
            'gender': 'F',
            'weight': '74.0',
            'height': '163.0',
            'hba1c': '7.3',
            'systolic_bp': 134,
            'diastolic_bp': 83,
            'heart_rate': 71,
            'fasting_glucose': 124,
            'ldl': 112,
            'creatinine': '0.8',
            'smoking_status': 'Never',
            'adherence': 'Good',
            'mobility_status': 'Independent',
            'cognitive_status': 'Normal',
            'fall_history': 'None',
            'medications': ['Metformin', 'Amlodipine'],
            'review_status': 'Reviewed',
            'last_assessed': datetime.date(2025, 7, 6),
        },
        {
            'patient_code': 'PT-M3Z5A1',
            'full_name': 'Yusuf Garba',
            'age': 76,
            'gender': 'M',
            'weight': '80.0',
            'height': '171.0',
            'hba1c': '8.5',
            'systolic_bp': 160,
            'diastolic_bp': 95,
            'heart_rate': 83,
            'fasting_glucose': 170,
            'ldl': 148,
            'creatinine': '1.3',
            'smoking_status': 'Former',
            'adherence': 'Moderate',
            'mobility_status': 'Independent',
            'cognitive_status': 'Mild Impairment',
            'fall_history': '1–2 falls',
            'medications': ['Glipizide', 'Losartan', 'Aspirin', 'Bisoprolol', 'Atorvastatin'],
            'review_status': 'Pending',
            'last_assessed': datetime.date(2025, 7, 12),
        },
        {
            'patient_code': 'PT-N4B6C2',
            'full_name': 'Adaeze Okafor',
            'age': 69,
            'gender': 'F',
            'weight': '66.0',
            'height': '159.0',
            'hba1c': '7.7',
            'systolic_bp': 142,
            'diastolic_bp': 87,
            'heart_rate': 73,
            'fasting_glucose': 138,
            'ldl': 120,
            'creatinine': '0.9',
            'smoking_status': 'Never',
            'adherence': 'Good',
            'mobility_status': 'Independent',
            'cognitive_status': 'Normal',
            'fall_history': 'None',
            'medications': ['Metformin', 'Lisinopril'],
            'review_status': 'Reviewed',
            'last_assessed': datetime.date(2025, 7, 5),
        },
        {
            'patient_code': 'PT-O5D7E3',
            'full_name': 'Haruna Suleiman',
            'age': 82,
            'gender': 'M',
            'weight': '73.0',
            'height': '167.0',
            'hba1c': '9.2',
            'systolic_bp': 174,
            'diastolic_bp': 100,
            'heart_rate': 89,
            'fasting_glucose': 196,
            'ldl': 165,
            'creatinine': '1.7',
            'smoking_status': 'Former',
            'adherence': 'Poor',
            'mobility_status': 'Wheelchair',
            'cognitive_status': 'Severe',
            'fall_history': '3+ falls',
            'medications': ['Insulin glargine', 'Insulin lispro', 'Furosemide', 'Warfarin', 'Digoxin', 'Allopurinol', 'Omeprazole'],
            'review_status': 'Urgent',
            'last_assessed': datetime.date(2025, 7, 15),
        },
    ]

    for patient in sample_patients:
        Patient.objects.update_or_create(
            patient_code=patient['patient_code'],
            defaults=patient,
        )


def unseed_patients(apps, schema_editor):
    Patient = apps.get_model('patient', 'Patient')
    Patient.objects.filter(patient_code__startswith='PT-').delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_code', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('hba1c', models.DecimalField(decimal_places=1, max_digits=4)),
                ('systolic_bp', models.PositiveIntegerField()),
                ('diastolic_bp', models.PositiveIntegerField()),
                ('heart_rate', models.PositiveIntegerField()),
                ('fasting_glucose', models.PositiveIntegerField()),
                ('ldl', models.PositiveIntegerField()),
                ('creatinine', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('smoking_status', models.CharField(blank=True, max_length=50)),
                ('adherence', models.CharField(blank=True, max_length=50)),
                ('mobility_status', models.CharField(blank=True, max_length=50)),
                ('cognitive_status', models.CharField(blank=True, max_length=50)),
                ('fall_history', models.CharField(blank=True, max_length=50)),
                ('medications', models.JSONField(blank=True, default=list)),
                ('review_status', models.CharField(choices=[('Urgent', 'Urgent'), ('Pending', 'Pending'), ('Reviewed', 'Reviewed')], default='Pending', max_length=20)),
                ('last_assessed', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'ordering': ['-last_assessed', 'full_name']},
        ),
        migrations.RunPython(seed_patients, unseed_patients),
    ]
